version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - rate-limiter-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  rate-limiter:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - DEFAULT_IP_LIMIT=5
      - DEFAULT_IP_BLOCK_DURATION=300
      - DEFAULT_TOKEN_LIMIT=10
      - DEFAULT_TOKEN_BLOCK_DURATION=300
      - SERVER_PORT=8080
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rate-limiter-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rate-limiter-network:
    driver: bridge

volumes:
  redis_data: 